// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/atdayev/submission-triage/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// AuditRepository is an autogenerated mock type for the AuditRepository type
type AuditRepository struct {
	mock.Mock
}

// Append provides a mock function with given fields: ctx, e
func (_m *AuditRepository) Append(ctx context.Context, e *model.AuditEntry) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AuditEntry) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListBySubmission provides a mock function with given fields: ctx, submissionID
func (_m *AuditRepository) ListBySubmission(ctx context.Context, submissionID string) ([]model.AuditEntry, error) {
	ret := _m.Called(ctx, submissionID)

	if len(ret) == 0 {
		panic("no return value specified for ListBySubmission")
	}

	var r0 []model.AuditEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.AuditEntry, error)); ok {
		return rf(ctx, submissionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.AuditEntry); ok {
		r0 = rf(ctx, submissionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AuditEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, submissionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuditRepository creates a new instance of AuditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditRepository {
	mock := &AuditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
