// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IngestControlRepository is an autogenerated mock type for the IngestControlRepository type
type IngestControlRepository struct {
	mock.Mock
}

// ClearFailure provides a mock function with given fields: ctx, uidValidity, uid
func (_m *IngestControlRepository) ClearFailure(ctx context.Context, uidValidity uint32, uid uint32) error {
	ret := _m.Called(ctx, uidValidity, uid)

	if len(ret) == 0 {
		panic("no return value specified for ClearFailure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32) error); ok {
		r0 = rf(ctx, uidValidity, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FirstBootAt provides a mock function with given fields: ctx, now
func (_m *IngestControlRepository) FirstBootAt(ctx context.Context, now time.Time) (time.Time, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for FirstBootAt")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (time.Time, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) time.Time); ok {
		r0 = rf(ctx, now)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecordFailure provides a mock function with given fields: ctx, uidValidity, uid, reason, now
func (_m *IngestControlRepository) RecordFailure(ctx context.Context, uidValidity uint32, uid uint32, reason string, now time.Time) (int, error) {
	ret := _m.Called(ctx, uidValidity, uid, reason, now)

	if len(ret) == 0 {
		panic("no return value specified for RecordFailure")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, string, time.Time) (int, error)); ok {
		return rf(ctx, uidValidity, uid, reason, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, string, time.Time) int); ok {
		r0 = rf(ctx, uidValidity, uid, reason, now)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, string, time.Time) error); ok {
		r1 = rf(ctx, uidValidity, uid, reason, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIngestControlRepository creates a new instance of IngestControlRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIngestControlRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IngestControlRepository {
	mock := &IngestControlRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
