// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/atdayev/submission-triage/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// OutboxRepository is an autogenerated mock type for the OutboxRepository type
type OutboxRepository struct {
	mock.Mock
}

// Enqueue provides a mock function with given fields: ctx, e
func (_m *OutboxRepository) Enqueue(ctx context.Context, e *model.OutboxEntry) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.OutboxEntry) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpirePending provides a mock function with given fields: ctx, olderThanUnixNano
func (_m *OutboxRepository) ExpirePending(ctx context.Context, olderThanUnixNano int64) (int64, error) {
	ret := _m.Called(ctx, olderThanUnixNano)

	if len(ret) == 0 {
		panic("no return value specified for ExpirePending")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, olderThanUnixNano)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, olderThanUnixNano)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, olderThanUnixNano)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpirePendingForSubmissions provides a mock function with given fields: ctx, submissionIDs, reason
func (_m *OutboxRepository) ExpirePendingForSubmissions(ctx context.Context, submissionIDs []string, reason string) (int64, error) {
	ret := _m.Called(ctx, submissionIDs, reason)

	if len(ret) == 0 {
		panic("no return value specified for ExpirePendingForSubmissions")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) (int64, error)); ok {
		return rf(ctx, submissionIDs, reason)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) int64); ok {
		r0 = rf(ctx, submissionIDs, reason)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string) error); ok {
		r1 = rf(ctx, submissionIDs, reason)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPending provides a mock function with given fields: ctx, id
func (_m *OutboxRepository) GetPending(ctx context.Context, id string) (*model.OutboxEntry, bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPending")
	}

	var r0 *model.OutboxEntry
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.OutboxEntry, bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.OutboxEntry); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OutboxEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListPending provides a mock function with given fields: ctx, now, retryCutoff, limit
func (_m *OutboxRepository) ListPending(ctx context.Context, now time.Time, retryCutoff time.Time, limit int) ([]model.OutboxEntry, error) {
	ret := _m.Called(ctx, now, retryCutoff, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPending")
	}

	var r0 []model.OutboxEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int) ([]model.OutboxEntry, error)); ok {
		return rf(ctx, now, retryCutoff, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int) []model.OutboxEntry); ok {
		r0 = rf(ctx, now, retryCutoff, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OutboxEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, int) error); ok {
		r1 = rf(ctx, now, retryCutoff, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkSent provides a mock function with given fields: ctx, id, version
func (_m *OutboxRepository) MarkSent(ctx context.Context, id string, version time.Time) error {
	ret := _m.Called(ctx, id, version)

	if len(ret) == 0 {
		panic("no return value specified for MarkSent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, id, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Prune provides a mock function with given fields: ctx, olderThanUnixNano
func (_m *OutboxRepository) Prune(ctx context.Context, olderThanUnixNano int64) (int64, error) {
	ret := _m.Called(ctx, olderThanUnixNano)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, olderThanUnixNano)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, olderThanUnixNano)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, olderThanUnixNano)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, status, attempts, lastErr
func (_m *OutboxRepository) Update(ctx context.Context, id string, status model.OutboxStatus, attempts int, lastErr string) error {
	ret := _m.Called(ctx, id, status, attempts, lastErr)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.OutboxStatus, int, string) error); ok {
		r0 = rf(ctx, id, status, attempts, lastErr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOutboxRepository creates a new instance of OutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OutboxRepository {
	mock := &OutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
