// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/atdayev/submission-triage/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// OutboxRepository is an autogenerated mock type for the OutboxRepository type
type OutboxRepository struct {
	mock.Mock
}

// Enqueue provides a mock function with given fields: ctx, e
func (_m *OutboxRepository) Enqueue(ctx context.Context, e *model.OutboxEntry) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.OutboxEntry) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListPending provides a mock function with given fields: ctx, olderThan, limit
func (_m *OutboxRepository) ListPending(ctx context.Context, olderThan time.Time, limit int) ([]model.OutboxEntry, error) {
	ret := _m.Called(ctx, olderThan, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPending")
	}

	var r0 []model.OutboxEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]model.OutboxEntry, error)); ok {
		return rf(ctx, olderThan, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) []model.OutboxEntry); ok {
		r0 = rf(ctx, olderThan, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OutboxEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = rf(ctx, olderThan, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, status, attempts, lastErr
func (_m *OutboxRepository) Update(ctx context.Context, id string, status model.OutboxStatus, attempts int, lastErr string) error {
	ret := _m.Called(ctx, id, status, attempts, lastErr)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.OutboxStatus, int, string) error); ok {
		r0 = rf(ctx, id, status, attempts, lastErr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOutboxRepository creates a new instance of OutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OutboxRepository {
	mock := &OutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
