// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/atdayev/submission-triage/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// SubmissionRepository is an autogenerated mock type for the SubmissionRepository type
type SubmissionRepository struct {
	mock.Mock
}

// FindByEmailReference provides a mock function with given fields: ctx, messageIDs
func (_m *SubmissionRepository) FindByEmailReference(ctx context.Context, messageIDs []string) (*model.Submission, bool, error) {
	ret := _m.Called(ctx, messageIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmailReference")
	}

	var r0 *model.Submission
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (*model.Submission, bool, error)); ok {
		return rf(ctx, messageIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) *model.Submission); ok {
		r0 = rf(ctx, messageIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Submission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) bool); ok {
		r1 = rf(ctx, messageIDs)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, []string) error); ok {
		r2 = rf(ctx, messageIDs)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByDeterministicID provides a mock function with given fields: ctx, deterministicID
func (_m *SubmissionRepository) FindByDeterministicID(ctx context.Context, deterministicID string) (*model.Submission, error) {
	ret := _m.Called(ctx, deterministicID)

	if len(ret) == 0 {
		panic("no return value specified for FindByDeterministicID")
	}

	var r0 *model.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Submission, error)); ok {
		return rf(ctx, deterministicID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Submission); ok {
		r0 = rf(ctx, deterministicID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Submission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, deterministicID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCompletedBefore provides a mock function with given fields: ctx, olderThanUnixNano, limit
func (_m *SubmissionRepository) ListCompletedBefore(ctx context.Context, olderThanUnixNano int64, limit int) ([]model.Submission, error) {
	ret := _m.Called(ctx, olderThanUnixNano, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListCompletedBefore")
	}

	var r0 []model.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) ([]model.Submission, error)); ok {
		return rf(ctx, olderThanUnixNano, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) []model.Submission); ok {
		r0 = rf(ctx, olderThanUnixNano, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Submission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = rf(ctx, olderThanUnixNano, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListEscalatedSince provides a mock function with given fields: ctx, sinceUnixNano, limit
func (_m *SubmissionRepository) ListEscalatedSince(ctx context.Context, sinceUnixNano int64, limit int) ([]model.Submission, error) {
	ret := _m.Called(ctx, sinceUnixNano, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListEscalatedSince")
	}

	var r0 []model.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) ([]model.Submission, error)); ok {
		return rf(ctx, sinceUnixNano, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) []model.Submission); ok {
		r0 = rf(ctx, sinceUnixNano, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Submission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = rf(ctx, sinceUnixNano, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListStale provides a mock function with given fields: ctx, olderThanUnixNano, limit
func (_m *SubmissionRepository) ListStale(ctx context.Context, olderThanUnixNano int64, limit int) ([]model.Submission, error) {
	ret := _m.Called(ctx, olderThanUnixNano, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListStale")
	}

	var r0 []model.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) ([]model.Submission, error)); ok {
		return rf(ctx, olderThanUnixNano, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) []model.Submission); ok {
		r0 = rf(ctx, olderThanUnixNano, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Submission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = rf(ctx, olderThanUnixNano, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertEmail provides a mock function with given fields: ctx, e
func (_m *SubmissionRepository) UpsertEmail(ctx context.Context, e *model.Email) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for UpsertEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Email) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertSubmission provides a mock function with given fields: ctx, s
func (_m *SubmissionRepository) UpsertSubmission(ctx context.Context, s *model.Submission) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSubmission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Submission) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSubmissionRepository creates a new instance of SubmissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubmissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubmissionRepository {
	mock := &SubmissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
