// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/atdayev/submission-triage/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SubmissionRepository is an autogenerated mock type for the SubmissionRepository type
type SubmissionRepository struct {
	mock.Mock
}

// ClearExtractedTextForClosed provides a mock function with given fields: ctx, closedBeforeUnixNano
func (_m *SubmissionRepository) ClearExtractedTextForClosed(ctx context.Context, closedBeforeUnixNano int64) (int64, error) {
	ret := _m.Called(ctx, closedBeforeUnixNano)

	if len(ret) == 0 {
		panic("no return value specified for ClearExtractedTextForClosed")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, closedBeforeUnixNano)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, closedBeforeUnixNano)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, closedBeforeUnixNano)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClearReplyHash provides a mock function with given fields: ctx, submissionID
func (_m *SubmissionRepository) ClearReplyHash(ctx context.Context, submissionID string) error {
	ret := _m.Called(ctx, submissionID)

	if len(ret) == 0 {
		panic("no return value specified for ClearReplyHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, submissionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountOpen provides a mock function with given fields: ctx
func (_m *SubmissionRepository) CountOpen(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountOpen")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FilenameOnlyItems provides a mock function with given fields: ctx, submissionIDs
func (_m *SubmissionRepository) FilenameOnlyItems(ctx context.Context, submissionIDs []string) (map[string][]string, error) {
	ret := _m.Called(ctx, submissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for FilenameOnlyItems")
	}

	var r0 map[string][]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string][]string, error)); ok {
		return rf(ctx, submissionIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string][]string); ok {
		r0 = rf(ctx, submissionIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, submissionIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByDeterministicID provides a mock function with given fields: ctx, deterministicID
func (_m *SubmissionRepository) FindByDeterministicID(ctx context.Context, deterministicID string) (*model.Submission, error) {
	ret := _m.Called(ctx, deterministicID)

	if len(ret) == 0 {
		panic("no return value specified for FindByDeterministicID")
	}

	var r0 *model.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Submission, error)); ok {
		return rf(ctx, deterministicID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Submission); ok {
		r0 = rf(ctx, deterministicID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Submission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, deterministicID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByEmailReference provides a mock function with given fields: ctx, messageIDs
func (_m *SubmissionRepository) FindByEmailReference(ctx context.Context, messageIDs []string) (*model.Submission, bool, error) {
	ret := _m.Called(ctx, messageIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmailReference")
	}

	var r0 *model.Submission
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (*model.Submission, bool, error)); ok {
		return rf(ctx, messageIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) *model.Submission); ok {
		r0 = rf(ctx, messageIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Submission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) bool); ok {
		r1 = rf(ctx, messageIDs)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, []string) error); ok {
		r2 = rf(ctx, messageIDs)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindContentMatch provides a mock function with given fields: ctx, namedInsured, fromAddress, createdAfterUnixNano
func (_m *SubmissionRepository) FindContentMatch(ctx context.Context, namedInsured string, fromAddress string, createdAfterUnixNano int64) (*model.Submission, error) {
	ret := _m.Called(ctx, namedInsured, fromAddress, createdAfterUnixNano)

	if len(ret) == 0 {
		panic("no return value specified for FindContentMatch")
	}

	var r0 *model.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) (*model.Submission, error)); ok {
		return rf(ctx, namedInsured, fromAddress, createdAfterUnixNano)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) *model.Submission); ok {
		r0 = rf(ctx, namedInsured, fromAddress, createdAfterUnixNano)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Submission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = rf(ctx, namedInsured, fromAddress, createdAfterUnixNano)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBindSoon provides a mock function with given fields: ctx, effectiveAfterUnixNano, effectiveBeforeUnixNano, limit
func (_m *SubmissionRepository) ListBindSoon(ctx context.Context, effectiveAfterUnixNano int64, effectiveBeforeUnixNano int64, limit int) ([]model.Submission, error) {
	ret := _m.Called(ctx, effectiveAfterUnixNano, effectiveBeforeUnixNano, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListBindSoon")
	}

	var r0 []model.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int) ([]model.Submission, error)); ok {
		return rf(ctx, effectiveAfterUnixNano, effectiveBeforeUnixNano, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int) []model.Submission); ok {
		r0 = rf(ctx, effectiveAfterUnixNano, effectiveBeforeUnixNano, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Submission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, int) error); ok {
		r1 = rf(ctx, effectiveAfterUnixNano, effectiveBeforeUnixNano, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCompletedBefore provides a mock function with given fields: ctx, olderThanUnixNano, limit
func (_m *SubmissionRepository) ListCompletedBefore(ctx context.Context, olderThanUnixNano int64, limit int) ([]model.Submission, error) {
	ret := _m.Called(ctx, olderThanUnixNano, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListCompletedBefore")
	}

	var r0 []model.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) ([]model.Submission, error)); ok {
		return rf(ctx, olderThanUnixNano, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) []model.Submission); ok {
		r0 = rf(ctx, olderThanUnixNano, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Submission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = rf(ctx, olderThanUnixNano, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListEscalatedSince provides a mock function with given fields: ctx, sinceUnixNano, limit
func (_m *SubmissionRepository) ListEscalatedSince(ctx context.Context, sinceUnixNano int64, limit int) ([]model.Submission, error) {
	ret := _m.Called(ctx, sinceUnixNano, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListEscalatedSince")
	}

	var r0 []model.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) ([]model.Submission, error)); ok {
		return rf(ctx, sinceUnixNano, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) []model.Submission); ok {
		r0 = rf(ctx, sinceUnixNano, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Submission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = rf(ctx, sinceUnixNano, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListHeldIDs provides a mock function with given fields: ctx
func (_m *SubmissionRepository) ListHeldIDs(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListHeldIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOpen provides a mock function with given fields: ctx, limit
func (_m *SubmissionRepository) ListOpen(ctx context.Context, limit int) ([]model.Submission, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListOpen")
	}

	var r0 []model.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.Submission, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.Submission); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Submission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListStale provides a mock function with given fields: ctx, olderThanUnixNano, limit
func (_m *SubmissionRepository) ListStale(ctx context.Context, olderThanUnixNano int64, limit int) ([]model.Submission, error) {
	ret := _m.Called(ctx, olderThanUnixNano, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListStale")
	}

	var r0 []model.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) ([]model.Submission, error)); ok {
		return rf(ctx, olderThanUnixNano, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) []model.Submission); ok {
		r0 = rf(ctx, olderThanUnixNano, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Submission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = rf(ctx, olderThanUnixNano, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListStalledBefore provides a mock function with given fields: ctx, olderThanUnixNano, limit
func (_m *SubmissionRepository) ListStalledBefore(ctx context.Context, olderThanUnixNano int64, limit int) ([]model.Submission, error) {
	ret := _m.Called(ctx, olderThanUnixNano, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListStalledBefore")
	}

	var r0 []model.Submission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) ([]model.Submission, error)); ok {
		return rf(ctx, olderThanUnixNano, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) []model.Submission); ok {
		r0 = rf(ctx, olderThanUnixNano, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Submission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = rf(ctx, olderThanUnixNano, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReplyBlockedIDs provides a mock function with given fields: ctx, submissionIDs
func (_m *SubmissionRepository) ReplyBlockedIDs(ctx context.Context, submissionIDs []string) ([]string, error) {
	ret := _m.Called(ctx, submissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for ReplyBlockedIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]string, error)); ok {
		return rf(ctx, submissionIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = rf(ctx, submissionIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, submissionIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetLastReplyAt provides a mock function with given fields: ctx, submissionID, t
func (_m *SubmissionRepository) SetLastReplyAt(ctx context.Context, submissionID string, t time.Time) error {
	ret := _m.Called(ctx, submissionID, t)

	if len(ret) == 0 {
		panic("no return value specified for SetLastReplyAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, submissionID, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetOnHold provides a mock function with given fields: ctx, submissionIDs, onHold
func (_m *SubmissionRepository) SetOnHold(ctx context.Context, submissionIDs []string, onHold bool) error {
	ret := _m.Called(ctx, submissionIDs, onHold)

	if len(ret) == 0 {
		panic("no return value specified for SetOnHold")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, bool) error); ok {
		r0 = rf(ctx, submissionIDs, onHold)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubmissionIDsByMessageIDs provides a mock function with given fields: ctx, messageIDs
func (_m *SubmissionRepository) SubmissionIDsByMessageIDs(ctx context.Context, messageIDs []string) ([]string, error) {
	ret := _m.Called(ctx, messageIDs)

	if len(ret) == 0 {
		panic("no return value specified for SubmissionIDsByMessageIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]string, error)); ok {
		return rf(ctx, messageIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = rf(ctx, messageIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, messageIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertEmail provides a mock function with given fields: ctx, e
func (_m *SubmissionRepository) UpsertEmail(ctx context.Context, e *model.Email) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for UpsertEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Email) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertSubmission provides a mock function with given fields: ctx, s
func (_m *SubmissionRepository) UpsertSubmission(ctx context.Context, s *model.Submission) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSubmission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Submission) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertSubmissionWithReply provides a mock function with given fields: ctx, s, reply
func (_m *SubmissionRepository) UpsertSubmissionWithReply(ctx context.Context, s *model.Submission, reply *model.OutboxEntry) error {
	ret := _m.Called(ctx, s, reply)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSubmissionWithReply")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Submission, *model.OutboxEntry) error); ok {
		r0 = rf(ctx, s, reply)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSubmissionRepository creates a new instance of SubmissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubmissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubmissionRepository {
	mock := &SubmissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
